server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_CLIENT_HOST}:${EUREKA_CLIENT_PORT}/eureka/

spring:
  application:
    name: ORDER-SERVICE
  data:
    mongodb:
      uri: mongodb://${DB_HOST}:${DB_PORT}/${DB_NAME}

  kafka:
    consumer:
      auto-offset-reset: earliest
  cloud:
    function:
      definition:
        "orderNotificationHandle"
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST}:${KAFKA_PORT}
      bindings:
        orderNotificationHandle-in-0:
          destination: order.notify.action
          content-type: application.json

    compatibility-verifier:
      enabled: false