server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_CLIENT_HOST}:${EUREKA_CLIENT_PORT}/eureka/

spring:
  application:
    name: NOTIFICATION-SERVICE
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    #    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: ${DB_DEFAULT_SCHEMA}

  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
  cache:
    type: redis

  kafka:
    consumer:
      auto-offset-reset: latest
  cloud:
    function:
      definition:
        "orderNotificationHandle"
    stream:
      bindings:
        orderNotificationHandle-in-0:
          destination: order.notify.action
          content-type: application/json
      kafka:
        binder:
          brokers: ${KAFKA_HOST}:${KAFKA_PORT}

    compatibility-verifier:
      enabled: false