server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_CLIENT_HOST}:${EUREKA_CLIENT_PORT}/eureka/

application:
  firebase:
    bucket-name: hau-ecommerce.appspot.com
    image-url: "https://firebasestorage.googleapis.com/v0/b/%s/o/%s?alt=media"

spring:
  application:
    name: AUTH-SERVICE

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: ${DB_DEFAULT_SCHEMA}

  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
      url: ${REDIS_URL}
      password: ${REDIS_PASSWORD}
  cache:
    type: redis

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 033f662cdda792dd4afd
            client-secret:
          google:
            client-id: 723628015267-4a8vs53icimlq4dsvafrhq3sf1tdpvu2.apps.googleusercontent.com
            client-secret:

  kafka:
#    listener: PLAINTEXT://kafka:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
  cloud:
    function:
      definition: avatarProcess
    stream:
      bindings:
        avatarProcess-in-0:
          destination: user-avatar-response
          content-type: application/json
      kafka:
        binder:
          brokers: ${KAFKA_HOST}:${KAFKA_PORT}

    compatibility-verifier:
      enabled: false

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 5MB