EUREKA_CLIENT_HOST: eureka-server
EUREKA_CLIENT_PORT: 8761

DB_HOST: localhost
DB_PORT: 5432
DB_NAME: ecommerce_dev
DB_DEFAULT_SCHEMA: dev
DB_USERNAME: postgres
DB_PASSWORD: 1234

KAFKA_HOST: kafka
KAFKA_PORT: 9092

REDIS_HOST: redis
REDIS_PORT: 6379
REDIS_PASSWORD: 234n2j2n
REDIS_URL: redis://redis:6379