server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_CLIENT_HOST}:${EUREKA_CLIENT_PORT}/eureka/

application:
  firebase:
    bucket-name: hau-ecommerce.appspot.com
    image-url: "https://firebasestorage.googleapis.com/v0/b/%s/o/%s?alt=media"

spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    #    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: ${DB_DEFAULT_SCHEMA}

  kafka:
    consumer:
      auto-offset-reset: latest
  cloud:
    function:
      definition:
        "productImageProcess;\
        serialNumberAction;\
        categoryImageProcess;\
        reduceQuantity"
    stream:
      bindings:
        productImageProcess-in-0:
          destination: product-image-response
          content-type: application/json
        serialNumberAction-in-0:
          destination: serials-action-request
          content-type: application/json
        categoryImageProcess-in-0:
          destination: category-image-response
          content-type: application/json
        reduceQuantity-in-0:
          destination: order.reduce.prduct.quantity
          content-type: application/json
      kafka:
        binder:
          brokers: ${KAFKA_HOST}:${KAFKA_PORT}

    compatibility-verifier:
      enabled: false